#include "IR_Remote.h"

static const uint8_t IR_PROTOCOL_DEFAULTS[IR_ACTION_COUNT] = {
  IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY,
  IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY,
  IR_PROTOCOL_UNKNOWN, IR_PROTOCOL_UNKNOWN, IR_PROTOCOL_UNKNOWN,
  IR_PROTOCOL_UNKNOWN, IR_PROTOCOL_UNKNOWN
};

static const uint16_t IR_ADDRESS_DEFAULTS[IR_ACTION_COUNT] = {
  IR_ADDRESS, IR_ADDRESS, IR_ADDRESS, IR_ADDRESS,
  IR_ADDRESS, IR_ADDRESS, IR_ADDRESS, IR_ADDRESS,
  0, 0, 0, 0, 0
};

static const uint8_t IR_COMMAND_DEFAULTS[IR_ACTION_COUNT] = {
  IR_CMD_VOL_UP, IR_CMD_VOL_DOWN, IR_CMD_INPUT_UP, IR_CMD_INPUT_DOWN,
  IR_CMD_BAL_LEFT, IR_CMD_BAL_RIGHT, IR_CMD_MUTE, IR_CMD_STANDBY,
  0, 0, 0, 0, 0
};

uint8_t irProtocolMap[IR_ACTION_COUNT] = {
  IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY,
  IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY,
  IR_PROTOCOL_UNKNOWN, IR_PROTOCOL_UNKNOWN, IR_PROTOCOL_UNKNOWN,
  IR_PROTOCOL_UNKNOWN, IR_PROTOCOL_UNKNOWN
};

uint16_t irAddressMap[IR_ACTION_COUNT] = {
  IR_ADDRESS, IR_ADDRESS, IR_ADDRESS, IR_ADDRESS,
  IR_ADDRESS, IR_ADDRESS, IR_ADDRESS, IR_ADDRESS,
  0, 0, 0, 0, 0
};

uint8_t irCommandMap[IR_ACTION_COUNT] = {
  IR_CMD_VOL_UP, IR_CMD_VOL_DOWN, IR_CMD_INPUT_UP, IR_CMD_INPUT_DOWN,
  IR_CMD_BAL_LEFT, IR_CMD_BAL_RIGHT, IR_CMD_MUTE, IR_CMD_STANDBY,
  0, 0, 0, 0, 0
};

void resetIRMappingsToDefaults() {
  for (uint8_t i = 0; i < IR_ACTION_COUNT; i++) {
    irProtocolMap[i] = IR_PROTOCOL_DEFAULTS[i];
    irAddressMap[i]  = IR_ADDRESS_DEFAULTS[i];
    irCommandMap[i]  = IR_COMMAND_DEFAULTS[i];
  }
}
