#include "IR_Remote.h"

uint8_t irProtocolMap[IR_ACTION_COUNT] = {
  IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY,
  IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY, IR_PROTOCOL_ANY
};

uint16_t irAddressMap[IR_ACTION_COUNT] = {
  IR_ADDRESS, IR_ADDRESS, IR_ADDRESS, IR_ADDRESS,
  IR_ADDRESS, IR_ADDRESS, IR_ADDRESS, IR_ADDRESS
};

uint8_t irCommandMap[IR_ACTION_COUNT] = {
  IR_CMD_VOL_UP,
  IR_CMD_VOL_DOWN,
  IR_CMD_INPUT_UP,
  IR_CMD_INPUT_DOWN,
  IR_CMD_BAL_LEFT,
  IR_CMD_BAL_RIGHT,
  IR_CMD_MUTE,
  IR_CMD_STANDBY
};
